name: Check PR
on: 
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node JS LTS
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install npm dependencies
      run: npm install

    - name: Setup additional dependencies
      run: npm run setup -s

    - name: Run default tests
      run: npm test -s
      env:
          GOOGLE_SERVICE_ACCOUNT_SECURE_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_SECURE_CREDENTIALS }}