name: Check PR
on: 
  pull_request:
    branches:
      - main
jobs:
  test-php-api:
    name: Test PHP API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node JS LTS
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install npm dependencies
      run: npm install

    - name: Setup additional dependencies
      run: npm run setup -s

    - name: Run default tests
      run: npm test -s
      env:
          GOOGLE_SERVICE_ACCOUNT_SECURE_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_SECURE_CREDENTIALS }}

  test-cdk-api:
    name: Test CDK API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node JS LTS
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install npm dependencies
      run: npm install
      working-directory: ./cdk-api

    - name: Run default tests
      run: npm test -s
      working-directory: ./cdk-api