name: Update All - Manual Deployment

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      reason:
        type: string
        description: 'Reason for deployment'     
        required: false
        default: 'I want to update all the data'

jobs:
  deploy:
    name: Update All
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node.js 18.x LTS
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install node modules in /
      run: npm ci

    - name: Install node modules in /deploy
      working-directory: deploy
      run: npm ci

    - name: Updated owned lists
      run: node run update-all
      env:
          GOOGLE_SERVICE_ACCOUNT_SECURE_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_SECURE_CREDENTIALS }}
          PLAYRECORD_API_USER: ${{ secrets.PLAYRECORD_API_USER }}
          PLAYRECORD_API_KEY: ${{ secrets.PLAYRECORD_API_KEY }}
          CONNECTED_WEB_PROD_SSO_CLIENT_ID: ${{ secrets.CONNECTED_WEB_PROD_SSO_CLIENT_ID }}
          CONNECTED_WEB_PROD_SSO_SECRET: ${{ secrets.CONNECTED_WEB_PROD_SSO_SECRET }}

    - name: Create data sets
      run: node run create-all

    - name: Setup /deploy/.ftp-pass
      run: ./scripts/setup/createFTPSecrets.sh "${{ secrets.FTP_USERNAME }}" "${{ secrets.FTP_PASSWORD }}"

    - name: Deploy Files
      run: node deploy live-data